apiVersion: v1
kind: Service
metadata:
  name: blue-app-service
  namespace: default  # Replace with your desired namespace
spec:
  selector:
    name: my-app  # Ensure this matches the label of your deployment
  ports:
    - protocol: TCP
      port: 80       # This is the port exposed by the service
      targetPort: 80  # This is the port the app is running on inside the container
