apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc  # PVC name
spec:
  accessModes:
    - ReadWriteMany  # PVC must match the PV's access mode (ReadWriteMany)
  resources:
    requests:
      storage: 5Gi  # Size requested from the PV
  storageClassName: ""  # No StorageClass specified, will bind to manual PV
