apiVersion: v1
kind: Pod
metadata:
  name: efs-pod
spec:
  containers:
    - name: efs-container
      image: busybox 
      command: ["sh", "-c", "while true; do echo hi hello > /mnt/efs/hello.txt; sleep 3600; done"]
      volumeMounts:
        - mountPath: /mnt/efs  # This is where the EFS volume will be mounted inside the container
          name: efs-volume
  volumes:
    - name: efs-volume
      persistentVolumeClaim:
        claimName: efs-pvc  # The PVC we created earlier
