apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany  # EFS supports ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Size should match the size of the PV
  storageClassName: efs-sc  # Reference to the storage class we created earlier
