apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: blue
      image: remyars/blue-app:latest
      ports:
      - containerPort: 80
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
   
