apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blue-app-pvc
spec:
  volumeName: blue-app-demo-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
